import json

questions = [
    # Preguntas con imágenes de ejemplo
    { 
        "question": "¿Qué famoso monumento es este?", 
        "answers": ["La Torre Eiffel", "El Coliseo", "La Estatua de la Libertad", "El Big Ben"], 
        "correct": 0,
        "image": "https://i.imgur.com/6L29zIm.jpeg"
    },
    { 
        "question": "¿Quién pintó este cuadro?", 
        "answers": ["Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Claude Monet"], 
        "correct": 2,
        "image": "https://i.imgur.com/O7f42d1.jpeg"
    },

    # Cultura General
    { "question": "¿Cuál es el río más largo del mundo?", "answers": ["Amazonas", "Nilo", "Misisipi", "Yangtsé"], "correct": 0 },
    { "question": "La capital de Francia es Roma.", "answers": ["Verdadero", "Falso"], "correct": 1 },
    { "question": "El agua hierve a 100 grados Celsius al nivel del mar.", "answers": ["Verdadero", "Falso"], "correct": 0 },
    { "question": "¿Quién escribió 'Don Quijote de la Mancha'?", "answers": ["García Márquez", "Shakespeare", "Homero", "Miguel de Cervantes"], "correct": 3 },
    { "question": "¿En qué continente se encuentra Egipto?", "answers": ["Asia", "África", "Europa", "Oceanía"], "correct": 1 },
    { "question": "¿Cuál es el océano más grande del mundo?", "answers": ["Atlántico", "Índico", "Pacífico", "Ártico"], "correct": 2 },
    { "question": "¿Qué planeta es conocido como el 'Planeta Rojo'?", "answers": ["Júpiter", "Marte", "Venus", "Saturno"], "correct": 1 },
    { "question": "La Mona Lisa fue pintada por...", "answers": ["Van Gogh", "Picasso", "Leonardo da Vinci", "Monet"], "correct": 2 },
    { "question": "¿Cuál es la capital de Australia?", "answers": ["Sídney", "Melbourne", "Canberra", "Perth"], "correct": 2 },
    { "question": "¿Qué gas es esencial para que respiremos?", "answers": ["Nitrógeno", "CO2", "Hidrógeno", "Oxígeno"], "correct": 3 },
    { "question": "¿Quién fue el primer hombre en pisar la Luna?", "answers": ["Yuri Gagarin", "Buzz Aldrin", "Michael Collins", "Neil Armstrong"], "correct": 3 },
    { "question": "¿En qué año comenzó la Segunda Guerra Mundial?", "answers": ["1914", "1939", "1945", "1929"], "correct": 1 },
    { "question": "La Gran Muralla China fue construida para protegerse de...", "answers": ["Los japoneses", "Los mongoles", "Los rusos", "Los coreanos"], "correct": 1 },
    { "question": "¿Qué instrumento musical tiene 88 teclas?", "answers": ["Guitarra", "Violín", "Piano", "Batería"], "correct": 2 },
    { "question": "¿Cuál es el país con más habitantes del mundo?", "answers": ["China", "India", "Estados Unidos", "Indonesia"], "correct": 1 },
    { "question": "¿Qué animal es un mamífero y puede volar?", "answers": ["Pingüino", "Avestruz", "Murciélago", "Pez volador"], "correct": 2 },
    { "question": "¿Quién es el autor de 'El Principito'?", "answers": ["J.K. Rowling", "Antoine de Saint-Exupéry", "Roald Dahl", "C.S. Lewis"], "correct": 1 },
    { "question": "¿Cuál es la montaña más alta del mundo?", "answers": ["K2", "Mont Blanc", "Everest", "Aconcagua"], "correct": 2 },
    { "question": "¿Qué civilización construyó las pirámides de Giza?", "answers": ["Griegos", "Romanos", "Persas", "Egipcios"], "correct": 3 },
    { "question": "¿Qué es la Vía Láctea?", "answers": ["Un planeta", "Una estrella", "Nuestra galaxia", "Un cometa"], "correct": 2 },
    { "question": "¿Cuál es el hueso más largo del cuerpo humano?", "answers": ["Tibia", "Fémur", "Húmero", "Peroné"], "correct": 1 },
    { "question": "¿Qué superhéroe de DC Comics es conocido como el 'Hombre de Acero'?", "answers": ["Batman", "Flash", "Superman", "Aquaman"], "correct": 2 },
    { "question": "¿Cuál es el ingrediente principal del guacamole?", "answers": ["Tomate", "Aguacate", "Cebolla", "Limón"], "correct": 1 },
    { "question": "¿En qué ciudad se encuentra el Coliseo Romano?", "answers": ["Atenas", "París", "Londres", "Roma"], "correct": 3 },
    { "question": "¿Cuál de estos instrumentos es de viento-madera?", "answers": ["Trompeta", "Trombón", "Clarinete", "Violín"], "correct": 2 },
    { "question": "La serie de libros de 'Harry Potter' fue escrita por...", "answers": ["Suzanne Collins", "J.R.R. Tolkien", "George R.R. Martin", "J.K. Rowling"], "correct": 3 },
    { "question": "¿Qué es la fotosíntesis?", "answers": ["La respiración de los animales", "La forma en que las plantas hacen su comida", "La evaporación del agua", "La formación de rocas"], "correct": 1 },
    { "question": "¿Qué país tiene forma de bota?", "answers": ["Grecia", "Italia", "Chile", "Noruega"], "correct": 1 },
    { "question": "¿Quién es considerado el 'Rey del Pop'?", "answers": ["Elvis Presley", "Michael Jackson", "Freddie Mercury", "Frank Sinatra"], "correct": 1 },
    { "question": "¿Qué es un Tsunami?", "answers": ["Un tornado de agua", "Una serie de olas gigantes", "Una tormenta eléctrica", "Un terremoto en tierra"], "correct": 1 },
    { "question": "La Estatua de la Libertad fue un regalo de ¿qué país a EE.UU.?", "answers": ["Reino Unido", "España", "Alemania", "Francia"], "correct": 3 },
    { "question": "¿Cuántos corazones tiene un pulpo?", "answers": ["Uno", "Dos", "Tres", "Cuatro"], "correct": 2 },
    { "question": "¿En qué país se originaron los Juegos Olímpicos?", "answers": ["Italia", "Egipto", "China", "Grecia"], "correct": 3 },
    { "question": "El personaje 'Sherlock Holmes' fue creado por...", "answers": ["Agatha Christie", "Arthur Conan Doyle", "Edgar Allan Poe", "Julio Verne"], "correct": 1 },
    { "question": "¿Cuál es el desierto más grande y cálido del mundo?", "answers": ["Gobi", "Atacama", "Kalahari", "Sahara"], "correct": 3 },
    { "question": "¿Cuál es la capital de Canadá?", "answers": ["Toronto", "Vancouver", "Montreal", "Ottawa"], "correct": 3 },
    { "question": "¿Qué elemento químico tiene el símbolo 'Au'?- ", "answers": ["Plata", "Argón", "Oro", "Aluminio"], "correct": 2 },
    { "question": "¿Qué deporte practica profesionalmente Rafael Nadal?", "answers": ["Fútbol", "Baloncesto", "Tenis", "Golf"], "correct": 2 },
    { "question": "¿Cómo se llama el proceso de convertir un líquido en gas?", "answers": ["Condensación", "Solidificación", "Fusión", "Evaporación"], "correct": 3 },
    { "question": "¿En qué ciudad está la famosa ópera 'La Scala'?", "answers": ["Viena", "París", "Milán", "Praga"], "correct": 2 },
    { "question": "¿Cuál es el animal terrestre más rápido?", "answers": ["León", "Tigre", "Guepardo", "Leopardo"], "correct": 2 },
    { "question": "¿Quién pintó 'El Guernica'?", "answers": ["Salvador Dalí", "Frida Kahlo", "Diego Rivera", "Pablo Picasso"], "correct": 3 },
    { "question": "¿Cuántos jugadores tiene un equipo de fútbol en el campo?", "answers": ["9", "10", "11", "12"], "correct": 2 },
    { "question": "¿Qué tipo de animal es la ballena?", "answers": ["Pez", "Mamífero", "Anfibio", "Reptil"], "correct": 1 },
    { "question": "¿Cuál es el libro sagrado del Islam?", "answers": ["La Torá", "La Biblia", "El Corán", "El Tripitaka"], "correct": 2 },
    { "question": "El Sol es una...", "answers": ["Estrella", "Planeta", "Galaxia", "Nebulosa"], "correct": 0 },
    { "question": "¿Cuál es la lengua más hablada en el mundo?", "answers": ["Inglés", "Español", "Chino Mandarín", "Hindi"], "correct": 2 },
    { "question": "¿Qué Beatle fue asesinado en 1980?", "answers": ["Paul McCartney", "George Harrison", "Ringo Starr", "John Lennon"], "correct": 3 },
    { "question": "¿Qué significan las siglas 'ADN'?", "answers": ["Ácido Desoxirribonucleico", "Amida de Nitrógeno", "Análisis Directo Numérico", "Azúcar de Naranja"], "correct": 0 },
    { "question": "¿Qué famoso científico desarrolló la teoría de la relatividad?", "answers": ["Isaac Newton", "Galileo Galilei", "Albert Einstein", "Nikola Tesla"], "correct": 2 },
    { "question": "¿Cuál es el color que resulta de mezclar azul y amarillo?", "answers": ["Rojo", "Naranja", "Marrón", "Verde"], "correct": 3 },
    { "question": "¿En qué continente está la selva del Amazonas?", "answers": ["Asia", "África", "América del Sur", "Australia"], "correct": 2 },
    { "question": "¿Cuál es el océano más pequeño del mundo?", "answers": ["Pacífico", "Atlántico", "Índico", "Ártico"], "correct": 3 },
    { "question": "¿En qué año llegó Cristóbal Colón a América?", "answers": ["1502", "1498", "1492", "1488"], "correct": 2 },
    { "question": "¿Cuál es el único mamífero que no puede saltar?", "answers": ["Rinoceronte", "Hipopótamo", "Jirafa", "Elefante"], "correct": 3 },
    { "question": "¿Qué país es el mayor productor de café del mundo?", "answers": ["Colombia", "Vietnam", "Etiopía", "Brasil"], "correct": 3 },
    { "question": "¿Qué famoso pintor se cortó una oreja?", "answers": ["Monet", "Van Gogh", "Gauguin", "Cézanne"], "correct": 1 },
    { "question": "La Torre Eiffel se encuentra en...", "answers": ["Londres", "Roma", "Berlín", "París"], "correct": 3 },
    { "question": "¿Cuál es el animal que más muertes humanas causa al año?", "answers": ["Tiburón", "Serpiente", "León", "Mosquito"], "correct": 3 },
    { "question": "¿Cuál es la capital de Japón?", "answers": ["Kioto", "Osaka", "Tokio", "Hiroshima"], "correct": 2 },
    { "question": "¿Qué elemento químico tiene el símbolo 'Fe'?- ", "answers": ["Fósforo", "Flúor", "Francio", "Hierro"], "correct": 3 },
    { "question": "¿Quién escribió 'Cien años de soledad'?", "answers": ["Mario Vargas Llosa", "Gabriel García Márquez", "Julio Cortázar", "Pablo Neruda"], "correct": 1 },
    { "question": "¿En qué año cayó el Muro de Berlín?", "answers": ["1987", "1989", "1991", "1993"], "correct": 1 },
    { "question": "¿Cuál es el metal más ligero?", "answers": ["Aluminio", "Titanio", "Litio", "Magnesio"], "correct": 2 },
    { "question": "¿Qué es un 'lustro'?", "answers": ["Un periodo de 5 años", "Un periodo de 10 años", "Un periodo de 50 años", "Un periodo de 100 años"], "correct": 0 },
    { "question": "¿Cuál es el país más grande del mundo por superficie?", "answers": ["China", "Canadá", "Estados Unidos", "Rusia"], "correct": 3 },
    { "question": "¿Quién dirigió la película 'Pulp Fiction'?", "answers": ["Martin Scorsese", "Steven Spielberg", "Quentin Tarantino", "James Cameron"], "correct": 2 },
    { "question": "¿Cuál es el nombre del proceso por el cual las plantas convierten la luz solar en energía?", "answers": ["Respiración celular", "Transpiración", "Fotosíntesis", "Germinación"], "correct": 2 },
    { "question": "¿Qué famoso artista es conocido por sus 'latas de sopa Campbell'?- ", "answers": ["Jackson Pollock", "Andy Warhol", "Roy Lichtenstein", "Jean-Michel Basquiat"], "correct": 1 },
    { "question": "¿Cuál es la capital de Argentina?", "answers": ["Santiago", "Bogotá", "Buenos Aires", "Lima"], "correct": 2 },
    { "question": "¿Qué gas de efecto invernadero es el más abundante en la atmósfera terrestre?", "answers": ["Dióxido de carbono", "Metano", "Óxido nitroso", "Vapor de agua"], "correct": 3 },
    { "question": "¿En qué deporte se utiliza un 'birdie'?", "answers": ["Tenis", "Bádminton", "Golf", "Críquet"], "correct": 1 },
    { "question": "¿Cuál es el nombre del primer satélite artificial lanzado al espacio?", "answers": ["Explorer 1", "Vanguard 1", "Sputnik 1", "Luna 1"], "correct": 2 },
    { "question": "¿Quién es el autor de la saga de libros 'El Señor de los Anillos'?", "answers": ["C.S. Lewis", "George R.R. Martin", "J.K. Rowling", "J.R.R. Tolkien"], "correct": 3 },
    { "question": "¿Cuál es el punto más bajo de la Tierra?", "answers": ["Fosa de las Marianas", "Valle de la Muerte", "Mar Muerto", "Depresión de Danakil"], "correct": 0 },
    { "question": "¿Qué instrumento tocaba Jimi Hendrix?", "answers": ["Batería", "Bajo", "Guitarra", "Teclado"], "correct": 2 },
    { "question": "¿Cuál es la moneda oficial del Reino Unido?", "answers": ["Euro", "Dólar", "Libra esterlina", "Franco"], "correct": 2 },
    { "question": "¿Qué civilización antigua es famosa por sus acueductos?", "answers": ["Griegos", "Egipcios", "Persas", "Romanos"], "correct": 3 },
    { "question": "¿Cuál es el planeta más grande de nuestro sistema solar?", "answers": ["Saturno", "Júpiter", "Neptuno", "Urano"], "correct": 1 },
    { "question": "¿Quién pintó la 'Noche Estrellada'?", "answers": ["Claude Monet", "Pablo Picasso", "Vincent van Gogh", "Salvador Dalí"], "correct": 2 },
    { "question": "¿Cuál es el animal nacional de la India?", "answers": ["Elefante", "León", "Tigre de Bengala", "Pavo real"], "correct": 2 },
    { "question": "¿En qué país se encuentra el Taj Mahal?", "answers": ["Pakistán", "India", "Bangladés", "Nepal"], "correct": 1 },
    { "question": "¿Cuál es el componente principal del Sol?", "answers": ["Oxígeno", "Carbono", "Hidrógeno", "Helio"], "correct": 2 },
    { "question": "¿Qué famoso dramaturgo escribió 'Romeo y Julieta'?", "answers": ["Christopher Marlowe", "Ben Jonson", "William Shakespeare", "John Webster"], "correct": 2 },
    { "question": "¿Cuál es el desierto más frío del mundo?", "answers": ["Gobi", "Patagónico", "Antártico", "Ártico"], "correct": 2 },
    { "question": "¿Qué es un 'origami'?", "answers": ["Un tipo de comida japonesa", "Un arte marcial", "El arte de doblar papel", "Un estilo de caligrafía"], "correct": 2 },
    { "question": "¿Cuál es la capital de Sudáfrica?", "answers": ["Johannesburgo", "Ciudad del Cabo", "Durban", "Pretoria"], "correct": 3 },
    { "question": "¿Qué banda de rock británica lanzó el álbum 'The Dark Side of the Moon'?", "answers": ["The Beatles", "Led Zeppelin", "Pink Floyd", "Queen"], "correct": 2 },
    { "question": "¿Cuál es el órgano más grande del cuerpo humano?", "answers": ["Hígado", "Cerebro", "Intestino", "Piel"], "correct": 3 },
    # Ciencia
    { "question": "¿Cuál es el símbolo químico del agua?", "answers": ["Ag", "O2", "H2O", "Au"], "correct": 2 },
    { "question": "¿Qué planeta es el más cercano al Sol?", "answers": ["Venus", "Tierra", "Mercurio", "Marte"], "correct": 2 },
    { "question": "¿Cuál es la velocidad de la luz?", "answers": ["300,000 km/s", "150,000 km/s", "500,000 km/s", "1,000,000 km/s"], "correct": 0 },
    { "question": "¿Qué tipo de energía se obtiene del viento?", "answers": ["Solar", "Hidráulica", "Geotérmica", "Eólica"], "correct": 3 },
    { "question": "¿Cuál es el metal más abundante en la corteza terrestre?", "answers": ["Hierro", "Aluminio", "Cobre", "Plomo"], "correct": 1 },
    { "question": "¿Qué estudia la entomología?", "answers": ["Peces", "Aves", "Insectos", "Plantas"], "correct": 2 },
    { "question": "¿Cuál es el ácido presente en los limones?", "answers": ["Ácido acético", "Ácido cítrico", "Ácido sulfúrico", "Ácido clorhídrico"], "correct": 1 },
    { "question": "¿Qué es la penicilina?", "answers": ["Un analgésico", "Un antibiótico", "Una vitamina", "Una hormona"], "correct": 1 },
    { "question": "¿Cuántos huesos tiene un ser humano adulto?", "answers": ["206", "210", "200", "212"], "correct": 0 },
    { "question": "¿Qué es la hematología?", "answers": ["El estudio de la sangre", "El estudio de los huesos", "El estudio de los músculos", "El estudio de los nervios"], "correct": 0 },
    # Historia
    { "question": "¿En qué año se descubrió América?", "answers": ["1492", "1500", "1488", "1512"], "correct": 0 },
    { "question": "¿Quién fue el primer emperador romano?", "answers": ["Julio César", "Augusto", "Nerón", "Calígula"], "correct": 1 },
    { "question": "¿Qué guerra duró 100 años?", "answers": ["La Guerra de los Cien Años", "La Primera Guerra Mundial", "La Segunda Guerra Mundial", "La Guerra de Vietnam"], "correct": 0 },
    { "question": "¿Dónde se originó la civilización azteca?", "answers": ["Perú", "México", "Egipto", "Grecia"], "correct": 1 },
    { "question": "¿Quién fue Juana de Arco?", "answers": ["Una reina de Inglaterra", "Una santa y heroína francesa", "Una escritora famosa", "Una pintora renacentista"], "correct": 1 },
    { "question": "¿Qué evento marcó el inicio de la Edad Media?", "answers": ["La caída del Imperio Romano", "El descubrimiento de América", "La invención de la imprenta", "La Revolución Francesa"], "correct": 0 },
    { "question": "¿Quién fue el líder de la Reforma Protestante?", "answers": ["Martín Lutero", "Juan Calvino", "Enrique VIII", "Ignacio de Loyola"], "correct": 0 },
    { "question": "¿En qué país se encuentra la ciudad de Petra?", "answers": ["Egipto", "Jordania", "Siria", "Irak"], "correct": 1 },
    { "question": "¿Qué faraón egipcio es famoso por su tumba intacta?", "answers": ["Ramsés II", "Cleopatra", "Tutankamón", "Akenatón"], "correct": 2 },
    { "question": "¿Qué fue el Renacimiento?", "answers": ["Un movimiento artístico y cultural", "Una guerra religiosa", "Una crisis económica", "Una pandemia"], "correct": 0 },
    # Geografía
    { "question": "¿Cuál es el desierto más grande del mundo?", "answers": ["El Sahara", "El Gobi", "El de Atacama", "El Antártico"], "correct": 3 },
    { "question": "¿En qué país se encuentra el Monte Fuji?", "answers": ["China", "Corea del Sur", "Japón", "Vietnam"], "correct": 2 },
    { "question": "¿Cuál es la capital de Rusia?", "answers": ["San Petersburgo", "Moscú", "Kiev", "Varsovia"], "correct": 1 },
    { "question": "¿Qué río pasa por París?", "answers": ["El Támesis", "El Danubio", "El Sena", "El Tíber"], "correct": 2 },
    { "question": "¿Cuál es el país más poblado de África?", "answers": ["Nigeria", "Egipto", "Sudáfrica", "Etiopía"], "correct": 0 },
    { "question": "¿En qué cordillera se encuentra el Aconcagua?", "answers": ["En los Alpes", "En los Andes", "En el Himalaya", "En las Montañas Rocosas"], "correct": 1 },
    { "question": "¿Cuál es la isla más grande del mundo?", "answers": ["Groenlandia", "Australia", "Borneo", "Madagascar"], "correct": 0 },
    { "question": "¿Qué país es conocido como la 'Tierra del Sol Naciente'?- ", "answers": ["China", "Japón", "Corea del Sur", "Tailandia"], "correct": 1 },
    { "question": "¿Cuál es la capital de Brasil?", "answers": ["Río de Janeiro", "São Paulo", "Brasilia", "Salvador"], "correct": 2 },
    { "question": "¿En qué continente se encuentra la Patagonia?", "answers": ["En América del Sur", "En África", "En Australia", "En Asia"], "correct": 0 },
    # Arte y Literatura
    { "question": "¿Quién pintó 'La última cena'?", "answers": ["Miguel Ángel", "Rafael", "Leonardo da Vinci", "Donatello"], "correct": 2 },
    { "question": "¿Qué escritor es famoso por sus novelas de misterio con Hércules Poirot?", "answers": ["Arthur Conan Doyle", "Agatha Christie", "Edgar Allan Poe", "Raymond Chandler"], "correct": 1 },
    { "question": "¿Quién es el autor de 'El viejo y el mar'?", "answers": ["Ernest Hemingway", "William Faulkner", "John Steinbeck", "F. Scott Fitzgerald"], "correct": 0 },
    { "question": "¿Qué movimiento artístico representa Salvador Dalí?", "answers": ["Cubismo", "Impresionismo", "Surrealismo", "Expresionismo"], "correct": 2 },
    { "question": "¿Quién escribió 'La Divina Comedia'?", "answers": ["Dante Alighieri", "Petrarca", "Boccaccio", "Maquiavelo"], "correct": 0 },
    { "question": "¿Qué banda de rock es conocida como 'Sus Satánicas Majestades'?- ", "answers": ["The Beatles", "The Rolling Stones", "Led Zeppelin", "Queen"], "correct": 1 },
    { "question": "¿Quién compuso 'Las cuatro estaciones'?", "answers": ["Mozart", "Bach", "Beethoven", "Vivaldi"], "correct": 3 },
    { "question": "¿Qué película ganó el primer Óscar a la Mejor Película?", "answers": ["Alas", "Lo que el viento se llevó", "Casablanca", "El mago de Oz"], "correct": 0 },
    { "question": "¿Quién es el autor de la escultura 'El Pensador'?", "answers": ["Miguel Ángel", "Donatello", "Rodin", "Bernini"], "correct": 2 },
    # Entretenimiento
    { "question": "¿En qué año se estrenó la primera película de Star Wars?", "answers": ["1977", "1980", "1983", "1975"], "correct": 0 },
    { "question": "¿Quién interpreta a Iron Man en el Universo Cinematográfico de Marvel?", "answers": ["Chris Evans", "Chris Hemsworth", "Mark Ruffalo", "Robert Downey Jr."], "correct": 3 },
    { "question": "¿Cuál es el nombre del protagonista de la serie 'Breaking Bad'?", "answers": ["Jesse Pinkman", "Saul Goodman", "Walter White", "Gus Fring"], "correct": 2 },
    { "question": "¿Qué videojuego es considerado el más vendido de la historia?", "answers": ["Tetris", "Minecraft", "Grand Theft Auto V", "Super Mario Bros."], "correct": 1 },
    { "question": "¿Quién es la cantante conocida como la 'Reina del Pop'?- ", "answers": ["Madonna", "Beyoncé", "Rihanna", "Lady Gaga"], "correct": 0 },
    { "question": "¿Qué serie de televisión tiene como lema 'Winter is Coming'?- ", "answers": ["The Walking Dead", "Breaking Bad", "Game of Thrones", "Stranger Things"], "correct": 2 },
    { "question": "¿Qué actor ha interpretado a James Bond en más películas?", "answers": ["Sean Connery", "Roger Moore", "Daniel Craig", "Pierce Brosnan"], "correct": 1 },
    { "question": "¿Cuál es el nombre del parque de atracciones de dinosaurios en 'Jurassic Park'?- ", "answers": ["Isla Nublar", "Isla Sorna", "Parque Jurásico", "Mundo Jurásico"], "correct": 0 },
    { "question": "¿Qué director de cine es conocido por películas como 'Tiburón', 'E.T.' y 'La lista de Schindler'?- ", "answers": ["Martin Scorsese", "Francis Ford Coppola", "Steven Spielberg", "Quentin Tarantino"], "correct": 2 },
    { "question": "¿Qué personaje de dibujos animados vive en una piña debajo del mar?", "answers": ["Mickey Mouse", "Bugs Bunny", "Bob Esponja", "Homer Simpson"], "correct": 2 },
    # Deportes
    { "question": "¿En qué país se inventó el fútbol?", "answers": ["Brasil", "Argentina", "Inglaterra", "España"], "correct": 2 },
    { "question": "¿Cuántos anillos de la NBA tiene Michael Jordan?", "answers": ["5", "6", "7", "8"], "correct": 1 },
    { "question": "¿Qué tenista ha ganado más torneos de Grand Slam?", "answers": ["Roger Federer", "Rafael Nadal", "Novak Djokovic", "Pete Sampras"], "correct": 2 },
    { "question": "¿En qué deporte destaca Usain Bolt?", "answers": ["Natación", "Atletismo", "Gimnasia", "Ciclismo"], "correct": 1 },
    { "question": "¿Cuál es el equipo de fútbol con más Champions League?", "answers": ["FC Barcelona", "AC Milan", "Liverpool FC", "Real Madrid"], "correct": 3 },
    { "question": "¿Cómo se llama el estadio del FC Barcelona?", "answers": ["Santiago Bernabéu", "Camp Nou", "Wanda Metropolitano", "San Mamés"], "correct": 1 },
    { "question": "¿En qué país se celebraron los primeros Juegos Olímpicos de la era moderna?", "answers": ["Grecia", "Francia", "Reino Unido", "Estados Unidos"], "correct": 0 },
    { "question": "¿Qué boxeador es conocido como 'The Greatest'?- ", "answers": ["Mike Tyson", "Muhammad Ali", "Floyd Mayweather", "Manny Pacquiao"], "correct": 1 },
    { "question": "¿En qué consiste un 'hat-trick' en el fútbol?", "answers": ["Marcar 2 goles en un partido", "Marcar 3 goles en un partido", "Marcar 4 goles en un partido", "Marcar 5 goles en un partido"], "correct": 1 },
    { "question": "¿Qué selección de fútbol ha ganado más Copas del Mundo?", "answers": ["Alemania", "Italia", "Argentina", "Brasil"], "correct": 3 },
    # Curiosidades
    { "question": "¿Cuál es el animal que tiene tres corazones?", "answers": ["El pulpo", "La sepia", "El calamar", "Todos los anteriores"], "correct": 3 },
    { "question": "¿De qué color es la sangre de los insectos?", "answers": ["Roja", "Azul", "Verde", "Amarillenta"], "correct": 3 },
    { "question": "¿Cuál es el único mamífero capaz de volar?", "answers": ["La ardilla voladora", "El murciélago", "El colugo", "El petauro del azúcar"], "correct": 1 },
    { "question": "¿Cuántos dientes tiene un caracol?", "answers": ["Ninguno", "Unos pocos", "Cientos", "Miles"], "correct": 3 },
    { "question": "¿Cuál es el animal más ruidoso del mundo?", "answers": ["La ballena azul", "El elefante", "El mono aullador", "El camarón pistola"], "correct": 3 },
    { "question": "¿Por qué los flamencos son rosas?", "answers": ["Por su genética", "Por su alimentación", "Porque se tiñen", "Es un misterio"], "correct": 1 },
    { "question": "¿Cuál es el animal con la mordida más fuerte?", "answers": ["El tiburón blanco", "El cocodrilo de agua salada", "La hiena", "El hipopótamo"], "correct": 1 },
    { "question": "¿Cuánto tiempo puede vivir una medusa?", "answers": ["Unos días", "Unos meses", "Unos años", "Algunas son inmortales"], "correct": 3 },
    { "question": "¿Cuál es el animal que duerme más horas al día?", "answers": ["El perezoso", "El koala", "El gato", "El murciélago"], "correct": 1 },
    { "question": "¿Qué animal tiene la lengua más larga en proporción a su cuerpo?", "answers": ["El oso hormiguero", "El camaleón", "El murciélago néctar", "El picaflor"], "correct": 1 },
    # Más Cultura General
    { "question": "¿Cuál es la capital de Turquía?", "answers": ["Estambul", "Ankara", "Izmir", "Bursa"], "correct": 1 },
    { "question": "¿Qué famoso científico propuso las tres leyes del movimiento?", "answers": ["Albert Einstein", "Galileo Galilei", "Isaac Newton", "Nikola Tesla"], "correct": 2 },
    { "question": "¿En qué país se encuentra la Torre de Pisa?", "answers": ["Francia", "Italia", "España", "Grecia"], "correct": 1 },
    { "question": "¿Cuál es el libro más vendido de la historia?", "answers": ["Don Quijote de la Mancha", "La Biblia", "El Señor de los Anillos", "Harry Potter y la piedra filosofal"], "correct": 1 },
    { "question": "¿Qué es un archipiélago?", "answers": ["Una cadena de montañas", "Un conjunto de islas", "Un tipo de relieve", "Un río subterráneo"], "correct": 1 },
    { "question": "¿Quién pintó el techo de la Capilla Sixtina?", "answers": ["Leonardo da Vinci", "Rafael", "Miguel Ángel", "Tiziano"], "correct": 2 },
    { "question": "¿Cuál es el idioma oficial de Brasil?", "answers": ["Español", "Portugués", "Inglés", "Francés"], "correct": 1 },
    { "question": "¿Qué es la aurora boreal?", "answers": ["Un fenómeno meteorológico", "Un tipo de estrella", "Un efecto óptico en la atmósfera", "Una constelación"], "correct": 2 },
    { "question": "¿Cuál es el metal más caro del mundo?", "answers": ["Oro", "Platino", "Rodio", "Paladio"], "correct": 2 },
    { "question": "¿Quién fue el primer ser humano en viajar al espacio?", "answers": ["Neil Armstrong", "Yuri Gagarin", "Buzz Aldrin", "John Glenn"], "correct": 1 },
    # Más Ciencia
    { "question": "¿Qué es la fisión nuclear?", "answers": ["La unión de dos átomos", "La división de un átomo", "La creación de un átomo", "La destrucción de un átomo"], "correct": 1 },
    { "question": "¿Cuál es el planeta más caliente del sistema solar?", "answers": ["Mercurio", "Venus", "Marte", "Júpiter"], "correct": 1 },
    { "question": "¿Qué es el número de Avogadro?", "answers": ["El número de átomos en un mol", "El número de planetas en el sistema solar", "La velocidad del sonido", "La constante de Planck"], "correct": 0 },
    { "question": "¿Qué es la clonación?", "answers": ["La creación de una copia genética", "La modificación de un gen", "La secuenciación del ADN", "La terapia génica"], "correct": 0 },
    { "question": "¿Qué es la materia oscura?", "answers": ["Una forma de materia que no emite luz", "Un tipo de agujero negro", "Una estrella de neutrones", "Una galaxia enana"], "correct": 0 },
    { "question": "¿Qué es la antimateria?", "answers": ["Una partícula con carga opuesta", "Una partícula sin carga", "Una partícula más pesada", "Una partícula más ligera"], "correct": 0 },
    { "question": "¿Qué es el bosón de Higgs?", "answers": ["Una partícula que da masa a otras partículas", "Una partícula que transmite la fuerza nuclear fuerte", "Una partícula que transmite la fuerza nuclear débil", "Una partícula que transmite la fuerza electromagnética"], "correct": 0 },
    { "question": "¿Qué es la teoría de cuerdas?", "answers": ["Una teoría que unifica la relatividad y la mecánica cuántica", "Una teoría que describe el origen del universo", "Una teoría que explica la materia oscura", "Una teoría que predice la existencia de universos paralelos"], "correct": 0 },
    { "question": "¿Qué es un exoplaneta?", "answers": ["Un planeta fuera de nuestro sistema solar", "Un planeta enano", "Un planeta gaseoso", "Un planeta rocoso"], "correct": 0 },
    { "question": "¿Qué es la biotecnología?", "answers": ["La aplicación de la tecnología a los seres vivos", "El estudio de la vida en otros planetas", "La creación de vida artificial", "La modificación del clima"], "correct": 0 },
    # Más Historia
    { "question": "¿Qué fue la Ruta de la Seda?", "answers": ["Una red de rutas comerciales", "Una campaña militar", "Un movimiento religioso", "Una exploración científica"], "correct": 0 },
    { "question": "¿Quién fue Alejandro Magno?", "answers": ["Un rey de Macedonia que conquistó un gran imperio", "Un filósofo griego", "Un emperador romano", "Un faraón egipcio"], "correct": 0 },
    { "question": "¿Qué fue la Peste Negra?", "answers": ["Una pandemia que asoló Europa en el siglo XIV", "Una guerra entre Inglaterra y Francia", "Una crisis económica en el Imperio Romano", "Una rebelión campesina en China"], "correct": 0 },
    { "question": "¿Qué fue la Ilustración?", "answers": ["Un movimiento intelectual que enfatizaba la razón", "Un estilo artístico del siglo XVIII", "Una reforma religiosa en el siglo XVI", "Una revolución política en el siglo XVII"], "correct": 0 },
    { "question": "¿Qué fue la Guerra Fría?", "answers": ["Un enfrentamiento político e ideológico entre EEUU y la URSS", "Una guerra mundial que involucró a todas las potencias", "Un conflicto armado en la península de Corea", "Una carrera espacial entre EEUU y la URSS"], "correct": 0 },
    { "question": "¿Quién fue Nelson Mandela?", "answers": ["Un activista contra el apartheid y presidente de Sudáfrica", "Un líder de los derechos civiles en Estados Unidos", "Un primer ministro de la India", "Un secretario general de las Naciones Unidas"], "correct": 0 },
    { "question": "¿Qué fue el Imperio Otomano?", "answers": ["Un imperio que controló gran parte del sudeste de Europa, Asia occidental y el norte de África", "Un imperio que se extendió por toda la península ibérica", "Un imperio que dominó el subcontinente indio", "Un imperio que unificó China"], "correct": 0 },
    { "question": "¿Qué fue la Revolución Industrial?", "answers": ["Un proceso de profundas transformaciones económicas y sociales", "Una rebelión de los trabajadores contra los dueños de las fábricas", "Una guerra por el control de las colonias", "Un descubrimiento científico que cambió el mundo"], "correct": 0 },
    { "question": "¿Quién fue Gengis Kan?", "answers": ["El fundador del Imperio Mongol", "Un emperador de China", "Un sultán de Egipto", "Un rey de Persia"], "correct": 0 },
    { "question": "¿Qué fue el Apartheid?", "answers": ["Un sistema de segregación racial en Sudáfrica", "Un movimiento por los derechos de las mujeres", "Una política de expansión territorial", "Una doctrina religiosa"], "correct": 0 },
    # Más Geografía
    { "question": "¿Cuál es el lago más profundo del mundo?", "answers": ["El lago Baikal", "El lago Tanganica", "El lago Superior", "El mar Caspio"], "correct": 0 },
    { "question": "¿Cuál es la cascada más alta del mundo?", "answers": ["El Salto Ángel", "Las cataratas del Niágara", "Las cataratas de Iguazú", "Las cataratas Victoria"], "correct": 0 },
    { "question": "¿Cuál es el volcán más activo del mundo?", "answers": ["El Kilauea", "El Etna", "El Stromboli", "El Monte Fuji"], "correct": 0 },
    { "question": "¿Cuál es el país con más volcanes?", "answers": ["Indonesia", "Japón", "Estados Unidos", "Chile"], "correct": 0 },
    { "question": "¿Cuál es el río más caudaloso del mundo?", "answers": ["El Amazonas", "El Congo", "El Orinoco", "El Paraná"], "correct": 0 },
    { "question": "¿Cuál es el país con más islas?", "answers": ["Suecia", "Finlandia", "Canadá", "Indonesia"], "correct": 0 },
    { "question": "¿Cuál es la ciudad más poblada del mundo?", "answers": ["Tokio", "Delhi", "Shanghái", "São Paulo"], "correct": 0 },
    { "question": "¿Cuál es el país más pequeño del mundo?", "answers": ["Mónaco", "Nauru", "Tuvalu", "Ciudad del Vaticano"], "correct": 3 },
    { "question": "¿Cuál es el país con más fronteras terrestres?", "answers": ["Rusia", "China", "Brasil", "Alemania"], "correct": 1 },
    { "question": "¿Cuál es el punto más alejado del centro de la Tierra?", "answers": ["El Monte Everest", "El Chimborazo", "El K2", "El Aconcagua"], "correct": 1 },
    # Más Arte y Literatura
    { "question": "¿Quién escribió 'El retrato de Dorian Gray'?", "answers": ["Oscar Wilde", "Charles Dickens", "Jane Austen", "George Orwell"], "correct": 0 },
    { "question": "¿Qué pintor es considerado el padre del cubismo junto a Georges Braque?", "answers": ["Pablo Picasso", "Salvador Dalí", "Joan Miró", "Juan Gris"], "correct": 0 },
    { "question": "¿Qué novela comienza con la frase 'En un lugar de la Mancha, de cuyo nombre no quiero acordarme...'?- ", "answers": ["Don Quijote de la Mancha", "La Celestina", "El Lazarillo de Tormes", "El Buscón"], "correct": 0 },
    { "question": "¿Quién es el autor de la famosa escultura 'David'?", "answers": ["Miguel Ángel", "Donatello", "Bernini", "Cellini"], "correct": 0 },
    { "question": "¿Qué banda británica es conocida como los 'Fab Four'?- ", "answers": ["The Beatles", "The Rolling Stones", "The Who", "Queen"], "correct": 0 },
    { "question": "¿Quién escribió la obra de teatro 'La vida es sueño'?", "answers": ["Lope de Vega", "Calderón de la Barca", "Tirso de Molina", "Miguel de Cervantes"], "correct": 1 },
    { "question": "¿Qué artista es famoso por sus 'Móviles'?- ", "answers": ["Alexander Calder", "Jean Arp", "Henry Moore", "Constantin Brancusi"], "correct": 0 },
    { "question": "¿Qué libro de J.R.R. Tolkien precede a 'El Señor de los Anillos'?- ", "answers": ["El Hobbit", "El Silmarillion", "Los hijos de Húrin", "Cuentos inconclusos"], "correct": 0 },
    { "question": "¿Qué director de cine es famoso por sus películas de 'spaghetti western'?- ", "answers": ["Sergio Leone", "Federico Fellini", "Luchino Visconti", "Vittorio De Sica"], "correct": 0 },
    { "question": "¿Quién es la autora de la saga de novelas 'Los juegos del hambre'?- ", "answers": ["Suzanne Collins", "J.K. Rowling", "Stephenie Meyer", "Veronica Roth"], "correct": 0 },
    # Más Entretenimiento
    { "question": "¿Qué película de Disney fue la primera en ser lanzada en formato VHS?", "answers": ["Blancanieves y los siete enanitos", "Pinocho", "Fantasía", "Dumbo"], "correct": 0 },
    { "question": "¿Cuál es el nombre del actor que interpreta a Harry Potter?", "answers": ["Daniel Radcliffe", "Rupert Grint", "Tom Felton", "Matthew Lewis"], "correct": 0 },
    { "question": "¿Qué grupo de rock es famoso por su canción 'Bohemian Rhapsody'?- ", "answers": ["Queen", "Led Zeppelin", "Pink Floyd", "The Beatles"], "correct": 0 },
    { "question": "¿En qué videojuego aparece el personaje de Lara Croft?", "answers": ["Tomb Raider", "Uncharted", "The Last of Us", "Resident Evil"], "correct": 0 },
    { "question": "¿Qué serie de televisión trata sobre un profesor de química que se convierte en narcotraficante?", "answers": ["Breaking Bad", "The Wire", "Los Soprano", "Narcos"], "correct": 0 },
    { "question": "¿Qué actor interpretó al Joker en la película 'El Caballero Oscuro'?- ", "answers": ["Heath Ledger", "Jack Nicholson", "Jared Leto", "Joaquin Phoenix"], "correct": 0 },
    { "question": "¿Qué película de Quentin Tarantino está dividida en capítulos no cronológicos?", "answers": ["Pulp Fiction", "Reservoir Dogs", "Kill Bill", "Bastardos sin gloria"], "correct": 0 },
    { "question": "¿Qué personaje de Nintendo es un fontanero italiano?", "answers": ["Mario", "Luigi", "Wario", "Waluigi"], "correct": 0 },
    { "question": "¿Qué cantante es conocida como la 'Princesa del Pop'?- ", "answers": ["Britney Spears", "Christina Aguilera", "Jessica Simpson", "Mandy Moore"], "correct": 0 },
    # Aún Más Deportes
    { "question": "¿En qué deporte se utiliza un 'puck'?", "answers": ["Hockey sobre hielo", "Hockey sobre hierba", "Polo", "Lacrosse"], "correct": 0 },
    { "question": "¿Cuántos jugadores hay en un equipo de baloncesto en la cancha?", "answers": ["5", "6", "7", "11"], "correct": 0 },
    { "question": "¿Qué país ganó la primera Copa del Mundo de la FIFA en 1930?", "answers": ["Uruguay", "Argentina", "Brasil", "Italia"], "correct": 0 },
    { "question": "¿En qué ciudad se celebran los torneos de tenis de Wimbledon?", "answers": ["Londres", "París", "Nueva York", "Melbourne"], "correct": 0 },
    { "question": "¿Qué ciclista ha ganado más Tours de Francia?", "answers": ["Lance Armstrong", "Miguel Induráin", "Eddy Merckx", "Bernard Hinault"], "correct": 0 },
    { "question": "¿Cuál es el récord mundial de los 100 metros lisos masculinos?", "answers": ["9.58 segundos", "9.69 segundos", "9.72 segundos", "9.79 segundos"], "correct": 0 },
    { "question": "¿En qué deporte se conoce a Babe Ruth como una leyenda?", "answers": ["Béisbol", "Fútbol americano", "Baloncesto", "Hockey sobre hielo"], "correct": 0 },
    { "question": "¿Qué arte marcial es originario de Corea?", "answers": ["Taekwondo", "Karate", "Judo", "Kung Fu"], "correct": 0 },
    { "question": "¿Cuál es el evento principal del Super Bowl?", "answers": ["El partido de fútbol americano", "El espectáculo de medio tiempo", "Los anuncios publicitarios", "La ceremonia de premiación"], "correct": 0 },
    { "question": "¿Qué nadador ha ganado más medallas de oro olímpicas?", "answers": ["Michael Phelps", "Mark Spitz", "Ian Thorpe", "Ryan Lochte"], "correct": 0 },
    # Aún Más Curiosidades
    { "question": "¿Cuál es el único mamífero que no tiene cuerdas vocales?", "answers": ["La jirafa", "El perezoso", "El armadillo", "El topo"], "correct": 0 },
    { "question": "¿Cuál es el único planeta del sistema solar que no lleva el nombre de un dios romano o griego?", "answers": ["La Tierra", "Urano", "Neptuno", "Plutón"], "correct": 0 },
    { "question": "¿Cuál es el único hueso del cuerpo humano que no está conectado a ningún otro?", "answers": ["El hioides", "El coxis", "El esternón", "La rótula"], "correct": 0 },
    { "question": "¿Cuál es el único continente que se encuentra en los cuatro hemisferios?", "answers": ["África", "Asia", "Australia", "América del Sur"], "correct": 0 },
    { "question": "¿Cuál es el único animal que no puede enfermar?", "answers": ["El tiburón", "La langosta", "La medusa inmortal", "El tardígrado"], "correct": 0 },
    { "question": "¿Cuál es el único metal que es líquido a temperatura ambiente?", "answers": ["El mercurio", "El galio", "El cesio", "El francio"], "correct": 0 },
    { "question": "¿Cuál es el único país del mundo que empieza por la letra 'Z' en español?", "answers": ["Zambia", "Zimbabue", "Zaire", "No hay"], "correct": 1 },
    { "question": "¿Cuál es el único mamífero que puede ver el color rojo?", "answers": ["Los humanos", "Los primates", "Algunos marsupiales", "Ninguno"], "correct": 1 },
    { "question": "¿Cuál es el único órgano del cuerpo humano que puede regenerarse?", "answers": ["El hígado", "La piel", "El corazón", "El cerebro"], "correct": 0 },
    { "question": "¿Cuál es el único número que tiene el mismo número de letras que su valor?", "answers": ["Cinco", "Cuatro", "Tres", "Seis"], "correct": 0 },
    # Preguntas Adicionales 1
    { "question": "¿Qué es la caligrafía?", "answers": ["El arte de escribir a mano de forma bella", "Un estilo de pintura", "Una técnica de grabado", "Un tipo de escultura"], "correct": 0 },
    { "question": "¿Cuál es la capital de Escocia?", "answers": ["Edimburgo", "Glasgow", "Aberdeen", "Dundee"], "correct": 0 },
    { "question": "¿Quién escribió 'El diario de Ana Frank'?", "answers": ["Ana Frank", "Otto Frank", "Miep Gies", "Un autor anónimo"], "correct": 0 },
    { "question": "¿Qué es un haiku?", "answers": ["Un poema japonés de tres versos", "Una novela corta", "Una obra de teatro de un solo acto", "Una canción popular"], "correct": 0 },
    { "question": "¿Cuál es el instrumento nacional de Irlanda?", "answers": ["El arpa", "La gaita", "El violín", "La flauta"], "correct": 0 },
    { "question": "¿En qué ciudad se encuentra el Partenón?", "answers": ["Atenas", "Roma", "Estambul", "El Cairo"], "correct": 0 },
    { "question": "¿Quién pintó 'El nacimiento de Venus'?", "answers": ["Sandro Botticelli", "Leonardo da Vinci", "Miguel Ángel", "Rafael"], "correct": 0 },
    { "question": "¿Cuál es el género literario de 'La Odisea'?", "answers": ["Epopeya", "Tragedia", "Comedia", "Lírica"], "correct": 0 },
    { "question": "¿Qué es el flamenco?", "answers": ["Un género musical y de baile originario de Andalucía", "Un tipo de cante jondo", "Un estilo de guitarra", "Todas las anteriores"], "correct": 3 },
    { "question": "¿Quién es el autor de la famosa cita 'Pienso, luego existo'?- ", "answers": ["René Descartes", "Platón", "Aristóteles", "Sócrates"], "correct": 0 },
    # Preguntas Adicionales 2
    { "question": "¿Qué es la astrofísica?", "answers": ["La rama de la astronomía que estudia las propiedades físicas de los astros", "La búsqueda de vida extraterrestre", "La exploración de otros planetas", "La predicción del futuro a través de las estrellas"], "correct": 0 },
    { "question": "¿Cuál es la partícula subatómica con carga negativa?", "answers": ["El electrón", "El protón", "El neutrón", "El fotón"], "correct": 0 },
    { "question": "¿Qué es la genética?", "answers": ["El estudio de la herencia y los genes", "La manipulación del ADN", "La creación de organismos transgénicos", "La prevención de enfermedades hereditarias"], "correct": 0 },
    { "question": "¿Cuál es la fórmula química del dióxido de carbono?", "answers": ["CO2", "H2O", "O2", "NaCl"], "correct": 0 },
    { "question": "¿Qué es la paleontología?", "answers": ["El estudio de los fósiles", "La búsqueda de dinosaurios", "La reconstrucción de ecosistemas antiguos", "La datación de rocas"], "correct": 0 },
    { "question": "¿Cuál es la unidad básica de la vida?", "answers": ["La célula", "El átomo", "La molécula", "El tejido"], "correct": 0 },
    { "question": "¿Qué es la sismología?", "answers": ["El estudio de los terremotos", "La predicción de erupciones volcánicas", "La medición de la intensidad de los tsunamis", "La prevención de desastres naturales"], "correct": 0 },
    { "question": "¿Cuál es el planeta más alejado del Sol?", "answers": ["Neptuno", "Urano", "Saturno", "Júpiter"], "correct": 0 },
    { "question": "¿Qué es la botánica?", "answers": ["El estudio de las plantas", "El cultivo de flores", "El diseño de jardines", "La clasificación de árboles"], "correct": 0 },
    { "question": "¿Cuál es la estrella más cercana a la Tierra?", "answers": ["El Sol", "Próxima Centauri", "Alfa Centauri A", "Sirio"], "correct": 0 },
    # Preguntas Adicionales 3
    { "question": "¿Qué fue la batalla de Stalingrado?", "answers": ["Una batalla decisiva en el frente oriental de la Segunda Guerra Mundial", "Un punto de inflexión que detuvo el avance alemán en la Unión Soviética", "Una de las batallas más sangrientas de la historia", "Todas las anteriores"], "correct": 3 },
    { "question": "¿Quién fue Cleopatra?", "answers": ["La última reina del Antiguo Egipto", "Una amante de Julio César y Marco Antonio", "Una figura histórica famosa por su belleza e inteligencia", "Todas las anteriores"], "correct": 3 },
    { "question": "¿Qué fue la Inquisición española?", "answers": ["Un tribunal eclesiástico que perseguía la herejía", "Una institución que utilizó la tortura y la quema en la hoguera", "Un instrumento de control social y político de la monarquía", "Todas las anteriores"], "correct": 3 },
    { "question": "¿Quién fue Marco Polo?", "answers": ["Un mercader y explorador veneciano que viajó a China", "El autor de 'Los viajes de Marco Polo'", "Una fuente de inspiración para futuros exploradores como Cristóbal Colón", "Todas las anteriores"], "correct": 3 },
    { "question": "¿Qué fue el Imperio Inca?", "answers": ["El imperio más grande de la América precolombina", "Una civilización que construyó una red de caminos y ciudades en los Andes", "Un pueblo que adoraba al dios Sol", "Todas las anteriores"], "correct": 3 },
    { "question": "¿Quién fue Leonardo da Vinci?", "answers": ["Un polímata del Renacimiento italiano: pintor, escultor, arquitecto, músico, científico, inventor...", "El autor de 'La Gioconda' y 'La última cena'", "Un genio que se adelantó a su tiempo con sus ideas y diseños", "Todas las anteriores"], "correct": 3 },
    { "question": "¿Qué fue la batalla de Waterloo?", "answers": ["La batalla que supuso la derrota final de Napoleón Bonaparte", "El fin de las Guerras Napoleónicas y del Primer Imperio Francés", "Un enfrentamiento entre el ejército francés y una coalición liderada por el Duque de Wellington", "Todas las anteriores"], "correct": 3 },
    { "question": "¿Quién fue Juana la Loca?", "answers": ["Una reina de Castilla y Aragón que fue encerrada por su supuesta locura", "La madre del emperador Carlos V", "Una figura trágica marcada por los celos y las intrigas políticas", "Todas las anteriores"], "correct": 3 },
    { "question": "¿Qué fue la toma de la Bastilla?", "answers": ["Un evento simbólico que marcó el inicio de la Revolución Francesa", "La caída de una prisión que representaba el absolutismo monárquico", "Una revuelta popular que inspiró a otros países a luchar por la libertad", "Todas las anteriores"], "correct": 3 },
    { "question": "¿Quién fue Simón Bolívar?", "answers": ["Un líder militar y político que luchó por la independencia de varios países de América del Sur", "El fundador de la Gran Colombia", "Conocido como 'El Libertador'", "Todas las anteriores"], "correct": 3 },
    # Preguntas Adicionales 4
    { "question": "¿Cuál es la capital de Marruecos?", "answers": ["Rabat", "Casablanca", "Marrakech", "Fez"], "correct": 0 },
    { "question": "¿En qué país se encuentra el desierto de Sonora?", "answers": ["México y Estados Unidos", "Chile y Argentina", "Perú y Bolivia", "Brasil y Colombia"], "correct": 0 },
    { "question": "¿Cuál es la capital de Noruega?", "answers": ["Oslo", "Bergen", "Trondheim", "Stavanger"], "correct": 0 },
    { "question": "¿Cuál es el río más largo de Europa?", "answers": ["El Volga", "El Danubio", "El Rin", "El Dniéper"], "correct": 0 },
    { "question": "¿Cuál es la capital de Irán?", "answers": ["Teherán", "Isfahán", "Shiraz", "Tabriz"], "correct": 0 },
    { "question": "¿En qué continente se encuentra Madagascar?", "answers": ["África", "Asia", "Oceanía", "América del Sur"], "correct": 0 },
    { "question": "¿Cuál es la capital de Perú?", "answers": ["Lima", "Cuzco", "Arequipa", "Trujillo"], "correct": 0 },
    { "question": "¿Cuál es el mar que separa Europa de África?", "answers": ["El mar Mediterráneo", "El mar Rojo", "El mar Negro", "El mar Caspio"], "correct": 0 },
    { "question": "¿Cuál es la capital de Filipinas?", "answers": ["Manila", "Cebú", "Dávao", "Quezon City"], "correct": 0 },
    # Aún Más Arte y Literatura
    { "question": "¿Quién escribió 'El retrato de Dorian Gray'?", "answers": ["Oscar Wilde", "Charles Dickens", "Jane Austen", "George Orwell"], "correct": 0 },
    { "question": "¿Qué pintor es considerado el padre del cubismo junto a Georges Braque?", "answers": ["Pablo Picasso", "Salvador Dalí", "Joan Miró", "Juan Gris"], "correct": 0 },
    { "question": "¿Qué novela comienza con la frase 'En un lugar de la Mancha, de cuyo nombre no quiero acordarme...'?- ", "answers": ["Don Quijote de la Mancha", "La Celestina", "El Lazarillo de Tormes", "El Buscón"], "correct": 0 },
    { "question": "¿Quién es el autor de la famosa escultura 'David'?", "answers": ["Miguel Ángel", "Donatello", "Bernini", "Cellini"], "correct": 0 },
    { "question": "¿Qué banda británica es conocida como los 'Fab Four'?- ", "answers": ["The Beatles", "The Rolling Stones", "The Who", "Queen"], "correct": 0 },
    { "question": "¿Quién escribió la obra de teatro 'La vida es sueño'?", "answers": ["Lope de Vega", "Calderón de la Barca", "Tirso de Molina", "Miguel de Cervantes"], "correct": 1 },
    { "question": "¿Qué artista es famoso por sus 'Móviles'?- ", "answers": ["Alexander Calder", "Jean Arp", "Henry Moore", "Constantin Brancusi"], "correct": 0 },
    { "question": "¿Qué libro de J.R.R. Tolkien precede a 'El Señor de los Anillos'?- ", "answers": ["El Hobbit", "El Silmarillion", "Los hijos de Húrin", "Cuentos inconclusos"], "correct": 0 },
    { "question": "¿Qué director de cine es famoso por sus películas de 'spaghetti western'?- ", "answers": ["Sergio Leone", "Federico Fellini", "Luchino Visconti", "Vittorio De Sica"], "correct": 0 },
    { "question": "¿Quién es la autora de la saga de novelas 'Los juegos del hambre'?- ", "answers": ["Suzanne Collins", "J.K. Rowling", "Stephenie Meyer", "Veronica Roth"], "correct": 0 },
    # Aún Más Entretenimiento
    { "question": "¿Qué película de Disney fue la primera en ser lanzada en formato VHS?", "answers": ["Blancanieves y los siete enanitos", "Pinocho", "Fantasía", "Dumbo"], "correct": 0 },
    { "question": "¿Cuál es el nombre del actor que interpreta a Harry Potter?", "answers": ["Daniel Radcliffe", "Rupert Grint", "Tom Felton", "Matthew Lewis"], "correct": 0 },
    { "question": "¿Qué grupo de rock es famoso por su canción 'Bohemian Rhapsody'?- ", "answers": ["Queen", "Led Zeppelin", "Pink Floyd", "The Beatles"], "correct": 0 },
    { "question": "¿En qué videojuego aparece el personaje de Lara Croft?", "answers": ["Tomb Raider", "Uncharted", "The Last of Us", "Resident Evil"], "correct": 0 },
    { "question": "¿Qué serie de televisión trata sobre un profesor de química que se convierte en narcotraficante?", "answers": ["Breaking Bad", "The Wire", "Los Soprano", "Narcos"], "correct": 0 },
    { "question": "¿Qué actor interpretó al Joker en la película 'El Caballero Oscuro'?- ", "answers": ["Heath Ledger", "Jack Nicholson", "Jared Leto", "Joaquin Phoenix"], "correct": 0 },
    { "question": "¿Qué película de Quentin Tarantino está dividida en capítulos no cronológicos?", "answers": ["Pulp Fiction", "Reservoir Dogs", "Kill Bill", "Bastardos sin gloria"], "correct": 0 },
    { "question": "¿Qué personaje de Nintendo es un fontanero italiano?", "answers": ["Mario", "Luigi", "Wario", "Waluigi"], "correct": 0 },
    { "question": "¿Qué cantante es conocida como la 'Princesa del Pop'?- ", "answers": ["Britney Spears", "Christina Aguilera", "Jessica Simpson", "Mandy Moore"], "correct": 0 },
    # Aún Más Deportes
    { "question": "¿En qué deporte se utiliza un 'puck'?", "answers": ["Hockey sobre hielo", "Hockey sobre hierba", "Polo", "Lacrosse"], "correct": 0 },
    { "question": "¿Cuántos jugadores hay en un equipo de baloncesto en la cancha?", "answers": ["5", "6", "7", "11"], "correct": 0 },
    { "question": "¿Qué país ganó la primera Copa del Mundo de la FIFA en 1930?", "answers": ["Uruguay", "Argentina", "Brasil", "Italia"], "correct": 0 },
    { "question": "¿En qué ciudad se celebran los torneos de tenis de Wimbledon?", "answers": ["Londres", "París", "Nueva York", "Melbourne"], "correct": 0 },
    { "question": "¿Qué ciclista ha ganado más Tours de Francia?", "answers": ["Lance Armstrong", "Miguel Induráin", "Eddy Merckx", "Bernard Hinault"], "correct": 0 },
    { "question": "¿Cuál es el récord mundial de los 100 metros lisos masculinos?", "answers": ["9.58 segundos", "9.69 segundos", "9.72 segundos", "9.79 segundos"], "correct": 0 },
    { "question": "¿En qué deporte se conoce a Babe Ruth como una leyenda?", "answers": ["Béisbol", "Fútbol americano", "Baloncesto", "Hockey sobre hielo"], "correct": 0 },
    { "question": "¿Qué arte marcial es originario de Corea?", "answers": ["Taekwondo", "Karate", "Judo", "Kung Fu"], "correct": 0 },
    { "question": "¿Cuál es el evento principal del Super Bowl?", "answers": ["El partido de fútbol americano", "El espectáculo de medio tiempo", "Los anuncios publicitarios", "La ceremonia de premiación"], "correct": 0 },
    { "question": "¿Qué nadador ha ganado más medallas de oro olímpicas?", "answers": ["Michael Phelps", "Mark Spitz", "Ian Thorpe", "Ryan Lochte"], "correct": 0 },
    # Aún Más Curiosidades
    { "question": "¿Cuál es el único mamífero que no tiene cuerdas vocales?", "answers": ["La jirafa", "El perezoso", "El armadillo", "El topo"], "correct": 0 },
    { "question": "¿Cuál es el único planeta del sistema solar que no lleva el nombre de un dios romano o griego?", "answers": ["La Tierra", "Urano", "Neptuno", "Plutón"], "correct": 0 },
    { "question": "¿Cuál es el único hueso del cuerpo humano que no está conectado a ningún otro?", "answers": ["El hioides", "El coxis", "El esternón", "La rótula"], "correct": 0 },
    { "question": "¿Cuál es el único continente que se encuentra en los cuatro hemisferios?", "answers": ["África", "Asia", "Australia", "América del Sur"], "correct": 0 },
    { "question": "¿Cuál es el único animal que no puede enfermar?", "answers": ["El tiburón", "La langosta", "La medusa inmortal", "El tardígrado"], "correct": 0 },
    { "question": "¿Cuál es el único metal que es líquido a temperatura ambiente?", "answers": ["El mercurio", "El galio", "El cesio", "El francio"], "correct": 0 },
    { "question": "¿Cuál es el único país del mundo que empieza por la letra 'Z' en español?", "answers": ["Zambia", "Zimbabue", "Zaire", "No hay"], "correct": 1 },
    { "question": "¿Cuál es el único mamífero que puede ver el color rojo?", "answers": ["Los humanos", "Los primates", "Algunos marsupiales", "Ninguno"], "correct": 1 },
    { "question": "¿Cuál es el único órgano del cuerpo humano que puede regenerarse?", "answers": ["El hígado", "La piel", "El corazón", "El cerebro"], "correct": 0 },
    { "question": "¿Cuál es el único número que tiene el mismo número de letras que su valor?", "answers": ["Cinco", "Cuatro", "Tres", "Seis"], "correct": 0 }
]

# Remove duplicates
unique_questions = []
seen_questions = set()
for question in questions:
    question_text = question["question"]
    if question_text not in seen_questions:
        unique_questions.append(question)
        seen_questions.add(question_text)

# Add type to each question
for question in unique_questions:
    # Simple heuristic to determine question type
    is_true_false = len(question['answers']) == 2 and \
                    all(a.lower() in ['verdadero', 'falso'] for a in question['answers'])
    if is_true_false:
        question['type'] = 'true_false'
    else:
        question['type'] = 'multiple_choice'

with open('Quiz Venezuela.json', 'w', encoding='utf-8') as f:
    json.dump(unique_questions, f, ensure_ascii=False, indent=4)

print(f"Se han generado {len(unique_questions)} preguntas en el archivo Quiz Venezuela.json")